export { default as HomeScreen } from './home'
export { default as RestaurantScreen } from './restaurant'
export { default as DetailScreen } from './detail'
export { default as OrderScreen } from './order'
export { default as CheckoutScreen } from './checkout'
export { default as PaymentScreen } from './payment'
export { default as CardsScreen } from './cards'
export { default as AddressesScreen } from './addresses'
